import { Container } from './styles';

export const Article = () => (
  <Container>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel cum non repellat iste, nobis sit commodi et! Ea, est. Suscipit in ducimus fugiat quod minus, inventore nisi, necessitatibus, debitis doloribus dignissimos commodi! Doloremque iusto deleniti assumenda iste? Vitae alias accusantium, aliquid ex ad qui cupiditate beatae cum magnam temporibus consequatur maxime aut soluta, id assumenda odit reprehenderit mollitia blanditiis ab incidunt ipsam quod! Maiores earum ab autem. Minima illum nobis quidem tempora sequi omnis possimus accusamus molestiae ullam voluptas porro repellendus vitae, expedita doloribus suscipit. Est exercitationem doloribus eligendi enim ipsa eveniet, architecto nemo id, reiciendis quae iure! Consequatur praesentium ipsam voluptatibus sed reprehenderit perferendis quibusdam, officia dicta enim facere, laboriosam, modi illo repellat consequuntur aliquid animi voluptas accusamus assumenda provident aut adipisci omnis. Beatae ducimus temporibus quos similique repellendus id quaerat enim veniam necessitatibus nemo, dignissimos totam porro assumenda perspiciatis debitis, recusandae nulla molestiae quasi laboriosam, aliquid quam alias natus officia obcaecati. Impedit praesentium distinctio error et facilis ea magnam dicta fuga ullam vel laboriosam numquam dolorum sit hic reprehenderit optio neque recusandae voluptatum, maiores at architecto porro. Suscipit quam magni in necessitatibus! Facere quidem dolores nam eum odit rerum at, impedit culpa praesentium inventore cumque doloremque, suscipit dicta.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel cum non repellat iste, nobis sit commodi et! Ea, est. Suscipit in ducimus fugiat quod minus, inventore nisi, necessitatibus, debitis doloribus dignissimos commodi! Doloremque iusto deleniti assumenda iste? Vitae alias accusantium, aliquid ex ad qui cupiditate beatae cum magnam temporibus consequatur maxime aut soluta, id assumenda odit reprehenderit mollitia blanditiis ab incidunt ipsam quod! Maiores earum ab autem. Minima illum nobis quidem tempora sequi omnis possimus accusamus molestiae ullam voluptas porro repellendus vitae, expedita doloribus suscipit. Est exercitationem doloribus eligendi enim ipsa eveniet, architecto nemo id, reiciendis quae iure! Consequatur praesentium ipsam voluptatibus sed reprehenderit perferendis quibusdam, officia dicta enim facere, laboriosam, modi illo repellat consequuntur aliquid animi voluptas accusamus assumenda provident aut adipisci omnis. Beatae ducimus temporibus quos similique repellendus id quaerat enim veniam necessitatibus nemo, dignissimos totam porro assumenda perspiciatis debitis, recusandae nulla molestiae quasi laboriosam, aliquid quam alias natus officia obcaecati. Impedit praesentium distinctio error et facilis ea magnam dicta fuga ullam vel laboriosam numquam dolorum sit hic reprehenderit optio neque recusandae voluptatum, maiores at architecto porro. Suscipit quam magni in necessitatibus! Facere quidem dolores nam eum odit rerum at, impedit culpa praesentium inventore cumque doloremque, suscipit dicta.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel cum non repellat iste, nobis sit commodi et! Ea, est. Suscipit in ducimus fugiat quod minus, inventore nisi, necessitatibus, debitis doloribus dignissimos commodi! Doloremque iusto deleniti assumenda iste? Vitae alias accusantium, aliquid ex ad qui cupiditate beatae cum magnam temporibus consequatur maxime aut soluta, id assumenda odit reprehenderit mollitia blanditiis ab incidunt ipsam quod! Maiores earum ab autem. Minima illum nobis quidem tempora sequi omnis possimus accusamus molestiae ullam voluptas porro repellendus vitae, expedita doloribus suscipit. Est exercitationem doloribus eligendi enim ipsa eveniet, architecto nemo id, reiciendis quae iure! Consequatur praesentium ipsam voluptatibus sed reprehenderit perferendis quibusdam, officia dicta enim facere, laboriosam, modi illo repellat consequuntur aliquid animi voluptas accusamus assumenda provident aut adipisci omnis. Beatae ducimus temporibus quos similique repellendus id quaerat enim veniam necessitatibus nemo, dignissimos totam porro assumenda perspiciatis debitis, recusandae nulla molestiae quasi laboriosam, aliquid quam alias natus officia obcaecati. Impedit praesentium distinctio error et facilis ea magnam dicta fuga ullam vel laboriosam numquam dolorum sit hic reprehenderit optio neque recusandae voluptatum, maiores at architecto porro. Suscipit quam magni in necessitatibus! Facere quidem dolores nam eum odit rerum at, impedit culpa praesentium inventore cumque doloremque, suscipit dicta.

  </Container>
);
