import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout } from '../components/Layout';
import { Article } from '../components/Article';
import { AsideItem } from '../components/AsideItem';

import {
  Aside, Title, Container, ContentWraper,
} from '../styles/pages/Home';

// import * as posts from '../data';

const Home: NextPage = () => (
  <Container>
    <Head>
      <title>Template Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
      <ContentWraper>
        <article>
          <Title>LOREM</Title>
          <Article />
        </article>
        <Aside>
          <Title>LOREM</Title>
          <AsideItem />
          <AsideItem />
          <AsideItem />
        </Aside>
      </ContentWraper>
    </Layout>
  </Container>
);

export default Home;
