import Head from 'next/head';

import { Layout } from '../components/Layout';
import { Article } from '../components/Article';

import {
  Title, Container, ContentWraper,
} from '../styles/pages/Home';
import { AsideList } from '../components/AsideList';
import { getAllPosts, IPostData } from '../api';

interface Props {
  posts: {
    data:IPostData;
    content : string;
  }[]
}

const Home = ({ posts }:Props) => (
  <Container>
    <Head>
      <title>Template Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Layout>
      <ContentWraper>
        <article>
          <Title>LOREM</Title>
          <Article />
        </article>
        <AsideList posts={posts} />
      </ContentWraper>
    </Layout>
  </Container>
);

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
}

export default Home;
