import Head from 'next/head';

import { ArticleLayout } from '../components/ArticleLayout';

import {
  Container,
} from '../styles/pages/Home';
import { getAllPosts, IPostData } from '../api';

interface Props {
  posts: {
    data:IPostData;
    content : string;
  }[]
}

const Home = ({ posts }:Props) => (
  <Container>
    <Head>
      <title>Template Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <ArticleLayout posts={posts}>

      <p>hi</p>

    </ArticleLayout>
  </Container>
);

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
}

export default Home;
